//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeNotebookDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryNodes
    {
        public int HistoryNodeId { get; set; }
        public Nullable<int> NodeId { get; set; }
        public Nullable<int> ParentNodeId { get; set; }
        public string NodeXml { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public Nullable<System.DateTime> LastModificationDateTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
