//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeNotebookDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TreeNotebookEntities : DbContext
    {
        public TreeNotebookEntities()
            : base("name=TreeNotebookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Node> Nodes { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<ProjectsNode> ProjectsNodes { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<HistoryNodes> HistoryNodes { get; set; }
        public DbSet<HistoryProjectNode> HistoryProjectNodes { get; set; }
        public DbSet<HistoryProjects> HistoryProjects { get; set; }
    }
}
