//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATADataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamSuiteTest
    {
        public int TeamId { get; set; }
        public int SuiteId { get; set; }
        public int TestId { get; set; }
    
        public virtual Suite Suite { get; set; }
        public virtual Team Team { get; set; }
        public virtual Test Test { get; set; }
    }
}
