//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATADataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalPath
    {
        public AdditionalPath()
        {
            this.Projects = new HashSet<Project>();
        }
    
        public int AdditionalPathId { get; set; }
        public string TfsPath { get; set; }
        public string TfsUrl { get; set; }
    
        public virtual ICollection<Project> Projects { get; set; }
    }
}
