//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATADataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberRole
    {
        public MemberRole()
        {
            this.Members = new HashSet<Member>();
        }
    
        public int MemberRoleId { get; set; }
        public string Role { get; set; }
    
        public virtual ICollection<Member> Members { get; set; }
    }
}
