//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATADataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.TeamSuiteTests = new HashSet<TeamSuiteTest>();
            this.AgentMachines = new HashSet<AgentMachine>();
            this.Members = new HashSet<Member>();
            this.Projects = new HashSet<Project>();
        }
    
        public int TeamId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<TeamSuiteTest> TeamSuiteTests { get; set; }
        public virtual ICollection<AgentMachine> AgentMachines { get; set; }
        public virtual ICollection<Member> Members { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
    }
}
