//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATADataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResultRun
    {
        public int TestResultRunId { get; set; }
        public int ExecutionStatusId { get; set; }
        public string ExecutionLog { get; set; }
        public string ExecutionResultRunId { get; set; }
        public int TestId { get; set; }
        public System.TimeSpan Duration { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
    
        public virtual ExecutionStatus ExecutionStatus { get; set; }
        public virtual ExecutionResultRun ExecutionResultRun { get; set; }
        public virtual Test Test { get; set; }
    }
}
