//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATADataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecutionStatus
    {
        public ExecutionStatus()
        {
            this.SuiteResultRuns = new HashSet<SuiteResultRun>();
            this.TestResultRuns = new HashSet<TestResultRun>();
        }
    
        public int ExecutionStatusId { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<SuiteResultRun> SuiteResultRuns { get; set; }
        public virtual ICollection<TestResultRun> TestResultRuns { get; set; }
    }
}
