//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATADataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecutionResultRun
    {
        public ExecutionResultRun()
        {
            this.TestResultRuns = new HashSet<TestResultRun>();
        }
    
        public string ExecutionResultRunId { get; set; }
        public string ComputerName { get; set; }
        public int RanBy { get; set; }
        public int Total { get; set; }
        public Nullable<int> Executed { get; set; }
        public Nullable<int> Passed { get; set; }
        public Nullable<int> Failed { get; set; }
        public Nullable<int> NotExecuted { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime Finish { get; set; }
    
        public virtual ICollection<TestResultRun> TestResultRuns { get; set; }
        public virtual Member Member { get; set; }
    }
}
